# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Accelerate CMS
email: admin@acceleratedhk.com
description: Accelerate course materials
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cms.acceleratedhk.com" # the base hostname & protocol for your site
twitter_username: acceleratedhk
github_username:  acceleratedhk
future: true
# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
collections:
  web_dev_basic:
    output: true
    permalink: /web-dev-basic/:path.html
    title: "Web Development Fundamentals"
    shortname: "Web"
    indexurl: /web-dev-basic/
  data_science:
    output: true
    permalink: /data-science/:path.html
    title: "Data Science and Machine Learning"
    shortname: "Data Science"
    indexurl: /data-science/
  ux:
    output: true
    permalink: /ux/:path.html
    title: "User Experience"
    shortname: "UX"
    indexurl: /ux/
tipue_search:
  include:
    posts: false
    pages: false
    collections: [web_dev_basic, data_science,ux]