# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Digital Guidelines
email: duane_harrison@cathaypacific.com
description: Digital Guidelines
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://duaneharrison.github.io/digitalguidelines" # the base hostname & protocol for your site
twitter_username: duaneharrison
github_username:  duaneharrison
future: true
# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
collections:
  web_dev_basic:
    output: true
    permalink: /otherresources/:path.html
    title: "Other Resources"
    shortname: "otherresources"
    indexurl: /otherresoruces/
  data_science:
    output: true
    permalink: /data-science/:path.html
    title: "Web Accessibility Pattern Library"
    shortname: "Data Science"
    indexurl: /data-science/
  ux:
    output: true
    permalink: /ux/:path.html
    title: "Digital Guidelines"
    shortname: "UX"
    indexurl: /ux/
tipue_search:
  include:
    posts: false
    pages: false
    collections: [web_dev_basic, data_science,ux]